### ISSUE TITLE
Proper copyright license?

### ISSUE THREAD

**Issue by EmiliaBlasten** [ahbarnett/glspect#1]
I do like this spectrogram, however the license here is legally not too clear. Could you update the license to be one which is commonly used, for example the Apache 2.0 or others (for example from https://choosealicense.com/)?

Second question: you mention having done part of this work while working for a university. Do they hold the copyright for that part of the code? Some universities do for programs made while employed.

**Comment by ahbarnett** [comment]
Thanks for catching that. I added Apache v2. Dartmouth has no rights over this, and I personally own the copyright. I'll just add a comment re code I adapted...
